const mongoose = require("mongoose");

const availabilitySchema = new mongoose.Schema(
  {
    doctor: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Doctor",
      required: true,
    },

    date: {
      type: Date,
      required: true,
    },

    startTime: {
      type: String,
      required: true,
      trim: true,
    },

    endTime: {
      type: String,
      required: true,
      trim: true,
    },

    isBooked: {
      type: Boolean,
      default: false,
    },

    // Groups slots generated by one POST /api/availability/recurring call,
    // so the whole series can be managed (deleted) together. Single slots
    // created via POST / have this as null.
    seriesId: {
      type: mongoose.Schema.Types.ObjectId,
      default: null,
      index: true,
    },
  },
  {
    timestamps: true,
  }
);

const Availability = mongoose.model(
  "Availability",
  availabilitySchema
);

module.exports = Availability;